USGS-WiM/StreamStats-National

CHANGELOG.md
Closes #8 
Added empty CHANGELOG.md template in root based on template provided here: https://github.com/USGS-WiM/stnweb2/blob/dev/CHANGELOG.md.
=> Issue #8 - Add CHANGELOG.md

.eslintignore, .github/linters/.eslintrc.json, .github/linters/.stylelintrc.json, .github/workflows/build.yml, .github/workflows/linter.yml, CHANGELOG.md, angular.json, karma.conf.js, package-lock.json, package.json, src/app/app.component.html, src/app/app.component.spec.ts
~~Test pull request to see if what I have is working at all.~~
Updating comment: This seems to be working and can be reviewed. I also ran into an issue when testing where the 'should render title' test failed. I put in a placeholder for that to get it to pass.
=> working on #9

CHANGELOG.md, src/app/center-bottom-content/components-bottom/report-builder/workflow/workflow.component.ts, src/app/map/map.component.ts, src/assets/config.json, src/assets/workflows.json
Closes #56 
- Added fire hydrology workflow: in the interest of time (meeting FY deadline), I split the Fire Hydro workflow into 2 separate workflows
- Reconfigured workflow overlay control
- Added relevant burn layers
Known issues to fix later:
- Fire Hydrology is split into 2 separate workflows (issue #87)
- When you X out of a workflow, remove that workflow's overlay layers from the map (issue #88)
- Add map layers to the sidebar (issue #70)
=> Issue #56 Set Up Fire Hydrology Workflow

src/app/app.component.html, src/app/map/map.component.html, src/app/map/map.component.ts, src/app/shared/components/loader/loader.component.html, src/app/shared/components/loader/loader.component.scss, src/app/shared/components/loader/loader.component.ts, src/app/shared/services/loader.service.ts, src/app/shared/services/map.service.spec.ts, src/app/shared/services/map.service.ts, src/app/sidebar-left/sidebar-left.component.spec.ts, src/app/sidebar-right/sidebar-right.component.spec.ts, src/app/top-bar/top-bar.component.spec.ts
Added error checks to service calls:
- getting streamgage layer
- getting streamgage data
- getting delineation
- getting trace of fire perimeters
Added loader service so we can turn on and off loader from any component
=> Fixes #94 - checks for errors in requests

src/app/shared/services/map.service.ts
In a couple spots where errors can occur I added error messages to the toaster and stopped the loader page.
=> Added Error messages

src/app/app.component.html, src/app/app.component.ts, src/app/shared/interfaces/config/config.ts, src/assets/config.json
Closes #126 
- Adds content to the About modal
- Adds content to the Help modal
- The version number is now in the config file, so it can be shown in the About modal
=> Fixes #126 - Create content for About and Help modals for Beta release

code.json
Initial update of code.json. We will need to update this again for the Beta release, but this is a start.
=> Fixes #1 - Update code.json

src/app/map/map.component.ts
=> Fixes #134 - Query by Fire Perimeter workflow gives error "Must select a fire perimeter."

src/app/map/map.component.ts, src/assets/config.json
=> Fixes #138

src/app/app.component.ts, src/app/map/map.component.ts, src/app/shared/services/map.service.ts, src/assets/config.json
Closes #146 
In addition to wildland fire updates, added description and other search engine optimization keywords
=> Fixes #146 - Consider adding keyword "wildland fire" and using "wildland fire" term throughout app 

code.json, src/assets/config.json
=> Fixes #160 - Update code.json

CHANGELOG.md, package.json
- Update base-href in build script 
- Update changelog
=> v0.1.0 beta.1 release fixes

CHANGELOG.md, src/assets/config.json
Update Changelog for v1.1.0-beta Release
=> Dev into Staging

CHANGELOG.md, code.json, src/assets/config.json
=> Fixes #198 - Release v1.1.1-beta

CHANGELOG.md, src/assets/config.json
=> Fixes #185

README.md
=> Fixes #157 - Provide public web/map service URLs somewhere in the interface/documentation

CHANGELOG.md, src/app/map/map.component.ts
Only print the flow lines in the 'Query by Fire Perimeters' workflow.
=> Fixes #207 

CHANGELOG.md, code.json, src/assets/config.json
- Forests parameter from fire hydrology basin characteristics 
- ReadMe: project description, node version, deployment instructions, internal documentation
- Only print flow lines in 'Query by Fire Perimeters' workflow
- Authors in documentation
- Issue where basin characteristics were getting overwritten by subsequent workflows
- Typo in version number in the About pop-up
- Dead link in documentation
=> Release v1.2.0-beta

CHANGELOG.md, package.json
=> Fixes #216 - Fix search API library

CHANGELOG.md, src/app/shared/interfaces/config/config.ts, src/app/shared/services/map.service.ts, src/assets/config.json
=> Fixes #219

CHANGELOG.md, src/app/content-right/report/report.component.html, src/app/content-right/report/report.component.ts, src/app/map/map.component.ts
- Changed fire perimeters labels
- Saved updated labels and values in the map component to remove redundant code in the report component.
=> Fixes #117

CHANGELOG.md, src/app/content-right/content-right.component.html, src/app/content-right/report/report.component.html
Changed 'overview' to 'report'
Edited some formatting in the print modal. Edited some spacing. Fixed a bug where the text was not going to the end of the modal.
I tried to recreate the issue they were seeing with scenarios not showing up in the report but wasn't able to. I even tried that same fire perimeter in Petes image. I was able to get a report with all workflows. If we can recreate this, it would be helpful to see the console. **Created issue for this here https://github.com/USGS-WiM/StreamStats-National/issues/247**
[allworkflows.pdf](https://github.com/USGS-WiM/StreamStats-National/files/9974731/allworkflows.pdf)
=> Fixes #234

CHANGELOG.md, src/app/content-right/report/report.component.html, src/app/content-right/report/report.component.ts, src/app/map/map.component.ts, src/assets/config.json
- Only able to query visible fire perimeters
- Only able to select/trace one fire perimeter at a time. 
- Added layergroup to add all output workflow layers to. Removed this layergroup when workflow is complete to clean up map.
=> Fixes #235

CHANGELOG.md, src/app/content-right/report-builder/workflow/workflow.component.html, src/app/content-right/report-builder/workflow/workflow.component.scss, src/app/content-right/report-builder/workflow/workflow.component.ts, src/app/content-right/report/report.component.html, src/app/map/map.component.ts, src/app/shared/services/map.service.ts, src/app/shared/services/workflow.service.ts, src/assets/workflows.json
Closes #22 
- The "Delineation" workflow now computes selected basin characteristics
- Some checkboxes were changed to radio buttons, when only one option is allowed to be selected
=> Fixes #22 - Precomputed Basin Characteristics using lambda 

CHANGELOG.md, src/app/content-right/report-builder/workflow/workflow.component.html, src/app/content-right/report-builder/workflow/workflow.component.scss, src/app/content-right/report-builder/workflow/workflow.component.ts, src/app/content-right/report/report.component.html, src/app/map/map.component.ts, src/app/shared/services/map.service.ts, src/assets/workflows.json
Reverts USGS-WiM/StreamStats-National#249
=> Revert "Fixes #22 - Precomputed Basin Characteristics using lambda "

CHANGELOG.md, src/index.html
=> Fixes #248

CHANGELOG.md, src/app/map/map.component.ts, src/assets/config.json
=> #255 Turn off Burn Severity layer by default

CHANGELOG.md, src/app/content-right/report-builder/workflow/workflow.component.html, src/app/content-right/report-builder/workflow/workflow.component.ts, src/assets/workflows.json
Closes #258
This should fix the errors we were getting with https://github.com/USGS-WiM/StreamStats-National/pull/249.
=> #258 - Add radio buttons

CHANGELOG.md, src/app/app.component.spec.ts, src/app/content-right/report-builder/workflow/workflow.component.html, src/app/content-right/report-builder/workflow/workflow.component.spec.ts, src/app/content-right/report-builder/workflow/workflow.component.ts, src/app/content-right/report/report.component.html, src/app/content-right/report/report.component.ts, src/app/map/map.component.spec.ts, src/app/map/map.component.ts, src/app/shared/services/map.service.ts, src/app/shared/services/workflow.service.ts, src/assets/workflows.json
=> Fixes #22 Precomputed Basin Characteristics using lambda 

CHANGELOG.md, src/app/content-right/report-builder/workflow/workflow.component.ts, src/app/content-right/report/report.component.html, src/app/map/map.component.ts, src/app/shared/services/map.service.ts, src/assets/config.json, src/markers.scss
=> Closes #114 - Add gages to Fire Hydrology - Query by Fire Perimeter workflow

src/app/map-actions/map-actions.component.html, src/app/map-actions/map-actions.component.ts, src/app/shared/services/map.service.ts
Part of #238
I added some code so that the map-action component can get the current basemap, so it can show the indicator of which map is currently selected.
=> Get current basemap in map-actions component 
